variable "resource_group_name" {}
variable "name" {}
variable "location" {}
#variable "connected_resource_name" {}
variable "enviroment" {}
variable "application"   {}
variable "workload" {}
variable "instance" {}
variable "network_security_group_inbound_rules" {}
variable "network_security_group_outbound_rules" {}